# Generated by Django 5.2.3 on 2025-07-05 11:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_emploi', models.DateField()),
                ('categorie', models.CharField(choices=[('COACH', 'Coach'), ('MENAGE', 'Ménage'), ('AIDE_SOIGNANT', 'Aide-soignant'), ('AUTRE', 'Autre')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('type_reservation', models.CharField(choices=[('SEANCE', 'Séance'), ('ABONNEMENT', 'Abonnement')], max_length=20, verbose_name='Type de réservation')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('EMPLOYE', 'Employé'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbonnementClientPresentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('PAIEMENT_INACHEVE', 'Paiement inachevé'), ('PAIEMENT_TERMINE', 'Paiement terminé')], default='PAIEMENT_INACHEVE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EXPIRE', 'Expiré')], default='EN_COURS', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonnement')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_presentiels', to=settings.AUTH_USER_MODEL)),
                ('employe_creation', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ajoute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('abonnement_presentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_paiements', to='core.abonnementclientpresentiel')),
                ('employe', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_paiements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèce'), ('CARTE', 'Carte'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.abonnement')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonnement')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèce'), ('CARTE', 'Carte'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20)),
                ('abonnement_presentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_tranches', to='core.abonnementclientpresentiel')),
                ('employe', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_tranches_effectues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresencePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('date_jour', models.DateField()),
                ('employe', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(default='', max_length=100)),
                ('client_prenom', models.CharField(default='', max_length=100)),
                ('date_jour', models.DateField(default=django.utils.timezone.now)),
                ('nombre_heures', models.PositiveIntegerField(default=1)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'categorie': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personnel', verbose_name='Coach')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seance'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='factures/')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.abonnementclient')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='core.paiement')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.reservation')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='tickets/')),
                ('type_ticket', models.CharField(choices=[('ABONNEMENT', 'Abonnement'), ('SEANCE', 'Séance')], max_length=20)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.paiement')),
            ],
        ),
    ]
