# Generated by Django 5.1.8 on 2025-06-16 21:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]