# Generated by Django 5.1.8 on 2025-06-22 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personnel_rename_date_presencepersonnel_date_jour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencepersonnel',
            name='employe',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
