# Generated by Django 5.1.8 on 2025-06-22 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_presencepersonnel_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'categorie': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personnel'),
        ),
    ]
