# Generated by Django 5.1.8 on 2025-06-24 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_seance_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solde',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seance',
            name='client_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='client_prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='date_jour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='nombre_heures',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seance',
            name='paye_directement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('CARTE', 'Carte'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='tickets/')),
                ('type_ticket', models.CharField(choices=[('ABONNEMENT', 'Abonnement'), ('SEANCE', 'Séance')], max_length=20)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.paiement')),
            ],
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
