# Generated by Django 5.1.8 on 2025-06-26 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reservation_date_heure_souhaitee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_heure',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='paye_directement',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='titre',
        ),
        migrations.AlterField(
            model_name='seance',
            name='client_nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seance',
            name='client_prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_jour',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='seance',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(upload_to='factures/')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.abonnementclient')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='core.paiement')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.reservation')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='core.seance')),
            ],
        ),
    ]
