# Generated by Django 5.1.8 on 2025-06-29 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paiement_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementClientPresentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('PAIEMENT_INACHEVE', 'Paiement inachevé'), ('PAIEMENT_TERMINE', 'Paiement terminé')], default='PAIEMENT_INACHEVE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EXPIRE', 'Expiré')], default='EN_COURS', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonnement')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_presentiels', to=settings.AUTH_USER_MODEL)),
                ('employe_creation', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECE', 'Espèce'), ('CARTE', 'Carte'), ('CHEQUE', 'Chèque')], default='ESPECE', max_length=20)),
                ('abonnement_presentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_tranches', to='core.abonnementclientpresentiel')),
                ('employe', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_tranches_effectues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
