# Generated by Django 5.1.8 on 2025-06-29 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_abonnementclientpresentiel_paiementtranche'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ajoute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('abonnement_presentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_paiements', to='core.abonnementclientpresentiel')),
                ('employe', models.ForeignKey(blank=True, limit_choices_to={'role': 'EMPLOYE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_paiements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
