# Generated by Django 5.1.8 on 2025-06-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_telephone'),
        ('core', '0013_historiquepaiement'),
    ]

    operations = [
    ]
